### DISCUSSION TITLE
Какие бывают номера карт пациента и где их хранить

### DISCUSSION THREAD

**Discussion by eugenekogan-spb** [fhir-ru/core#150] [Административная РГ]
Предлагаю в этой дискуссии обсудить, какие номера есть у пациента в медицинской организации, на каких уровнях (услуга, случай, пациент) они находятся, и можно ли их использовать для идентификации.

Целью дискуссии является рекомендация по использованию (или не использованию) этих номеров при заполнении полей Identifier ресурсов Patient, Encounter, EposodeOfCare, Procedure

Можно обсудить следующие номера

Номер амбулаторной карты
Номер карты диспансерного наблюдения

Номер истории болезни стационарного больного
Номер по амбулаторному журналу приемного отделения 
Номер по журналу неопознанных приемного отделения

Номер по журналу исследований пациента (например, в кабинете КТ)
Номер по журналу исследований образцов пациента (лабораторному журналу)

Номер листа временной нетрудоспособности

**Comment by eugenekogan-spb** [comment]
Предлагаемое решение о месте хранения (из обсуждения на встрече http://fhir-ru.zendoc.me/meetings.2022-05-31):
- все номера карт пациента записываем в ресурс Пациент в качестве идентификаторов разного рода
- в каждом Encounter, любого уровня (от госпитализации до взятия крови) используем в качестве идентификатора номер этого случая в МИС

**Comment by Vrodvi** [comment]
Также предлагаю рассмотреть альтернативное решение по поводу номеров карт - указание номеров карт в качестве идентификаторов для одного из ресурсов в иерархии, построенной из EpisodeOfCare и Encounter, где
Encounter - это конкретный случай взаимодействия пациента с поставщиком мед.услуг, 
а EpisodeOfCare - это информация о контроле за пациентом некой мед. организацией (в рамках такого эпизода конкретных случаев может и не произойти).

Примеры таких иерархий и варианты размещения в них номеров карт:

### 1) Амбулаторное наблюдение.
С момента прикрепляется пациента за некоторой поликлиникой можно считать открытым "эпизод" (EpisodeOfCare), в качестве идентификатора эпизода можно указать номер амбулаторной карты.
Конкретные посещения пациентом поликлиники - это "случаи" (Encounter) в рамках такого "эпизода". Посещения будут иметь отдельный идентификатор - например, номер талона амбулаторного визита.

- [1..1] EpisodeOfCare (амбулаторное наблюдение за пациентом) **<= Тут указывается номер амбулаторной карты**
  - [0..*] Encounter (отдельное посещение поликлиники) <= Тут указывается номер талона


### 2) Госпитализация.
Госпитализация - это конкретный "случай" (Encounter) взаимодействие пациента со стационаром и на время этого взаимодействия заводится карта стационарного пациента.
Внутри госпитализации переводы пациента между отделения также являются "случаями".
"Эпизод" (EpisodeOfCare) также может быть оформлен. Например, для Дневных Стационаров, когда несколько отдельных госпитализаций в ДС объединяются вместе, поскольку являются продолжениями друг друга (например, несколько госпитализаций в ДС для проведения нескольких линий химиотерапевтического лечения по одному заболеванию).

- [0..1] EpisodeOfCare (объединение нескольких госпитализаций по одному заболеванию)
  - [1..*] Encounter (госпитализация) **<= Тут указывается номер карты стационарного пациента**
    - [1..*] Encounter (пребывание в отделении)

### 3) Диспансерное наблюдение.
С момента прикрепляется пациента за некотором диспансером можно считать открытым "эпизод" (EpisodeOfCare), в качестве идентификатора эпизода можно указать номер карты диспансерного наблюдения.
Конкретные посещения пациентом диспансера - это "случаи" (Encounter) в рамках такого "эпизода". Посещения будут иметь отдельный идентификатор.

- [1..1] EpisodeOfCare (диспансерное наблюдение за пациентом по одному заболеванию) **<= Тут указывается номер карты диспансерного наблюдения**
  - [0..*] Encounter (отдельное посещение диспансера)

### 4) Скорая медицинская помощь.
"Эпизод" (EpisodeOfCare) отсутствует, есть только фактический "случай" (Encounter) взаимодействия пациента с бригадой СМП.

- [0..0] EpisodeOfCare
  - [1..1] Encounter (выезд скорой медицинской помощи) **<= Тут указывается номер карты скорой медицинской помощи**

---

Таким образом, при необходимости указания номера некой медицинской карты, можно будет включить в Бандл ресурсов подходящий фрагмент соответствующей иерархии до ближайшего ресурса, содержащего номер карты.

НАПРИМЕР: 
- для протокола лабораторного исследования, выполненного в поликлинике, можно будет включить в Бандл ресурс Encounter (отдельное посещение поликлиники с номером талона в качестве идентификатора), а также связанный с ним ресурс EpisodeOfCare (с номером амбулаторной карты в качестве идентификатора).

**Reply by JustAsWalker** [reply]
Данное решение подходит структурно, хотя для реализации амбулаторных карт в данном случае мы несколько отдаляемся от смысла, который FHIR вкладывает в ресурс EpisodeOfCare:
> In many cases, this represents a period of time where the Healthcare Provider has some level of responsibility for the care of the patient regarding a **specific condition or problem**, even if not currently participating in an encounter.
...
The EpisodeOfCare enables the practitioner **to easily separate** the diabetes activities from the mental health problem's activities.

Если я всё правильно понимаю, то логика такая: пациент приходит с общими жалобами в поликлинику (по амбулаторной карте- АК) к терапевту (ресурс Encounter), тот направляет к врачу-специалисту (Encounter), в ходе обследования которым выясняется, что у пациента хроническое заболевание, по поводу которого он может приходить на периодические осмотры в рамках АК (Encounter), а в случае обострения пациента могут госпитализировать (иерархия Encounter'ов). И вот все эти посещения - стационарные и амбулаторные должны быть объединены одним EpisodeOfCare.

Но если вернуться к нашей проблеме и необходимости как-то закодировать сущность амбулаторной карты, то из всех обсужденных на данный момент решений вариант с EpisodeOfCare, который предлагала Александра на созвоне и который описал Виталий выше, подходит больше всех.
Из плюсов этого решения:
- тот факт, что EpisodeOfCare описывает некое длительное взаимодействие пациента с мед. учреждением (МУ), даже если пациенту не оказывается помощь
> The EpisodeOfCare Resource contains information about an association of a Patient with a Healthcare Provider for a period of time under which related healthcare activities **may** occur.

- связь EpisodeOfCare с ресурсами Account, что позволит понимать, чем отличаются две амбулаторные карты пациента в случае, если МУ заводит отдельные карты для платных услуг

**Reply by DmFadin** [reply]
EpisodeOfCare подразумевает взаимодействие возможно более чем с одним МУ - например визит в поликлинику, направление в лабораторию, потом вызов скорой и госпитализация, потом диспансерное наблюдение. Но при этом никто не запрещает пациенту одновременно с например с острым коронарным синдромом сломать ногу и обратиться в ту же поликлинику в травмпункт. Поэтому в предложенном варианте мы потеряем наиболее значимую как для плательщика так и для врача информацию о поводе обращения. Так что я бы предложил для номеров карт использовать Вар.1, а для  идентификаторов записей в картах соответственно EpisodeOfCare и Encounter.

**Comment by Vrodvi** [comment]
Предложено вынести на голосование три варианта ведения номеров карт пациента.
Во всех трёх вариантах представлены примеры указания номеров одной амбулаторной карты и одной стационарной карты в контексте одного амбулаторного приёма и одной госпитализации, соответственно.


# [ВАРИАНТ 1] Указание всех номеров карт как идентификатор пациента.
+: всё в одном месте
-: если указано более одного номера карты, то неясно к какой карте что относится
```
  resourceType: Patient
  identifier:
  - use: ''
    type: {}
    system: ''
    value: номер амбулаторной карты
    period:
      start: '2001-05-06'
    assigner: {}
  - use: ''
    type: {}
    system: ''
    value: номер стационарной карты
    period:
      start: '2001-05-06'
      end: '2001-05-16'
    assigner: {}
```

```
  resourceType: Encounter
  id: ID_амбулаторного_посещения
  class:
    display: ambulatory
```

```
  resourceType: Encounter
  id: ID_госпитализации
  class:
    display: outpatient 
```

# [ВАРИАНТ 2] Указание номеров карт как идентификатор в иерархии из ресурсов-Encounter.
+: удобно что номера карт только в одном типе ресурса (encounter), остальные ресурсы легко отнести к одному из encounter'ов
-: идеологически не очень правильно обозначать всё амбулаторное наблюдение как конкретный encounter

```
  resourceType: Encounter
  id: ID_амбулаторного_наблюдения
  identifier:
  - use: ''
    type: {}
    system: ''
    value: номер амбулаторной карты
    period:
      start: '2001-05-06'
    assigner: {}
  class:
    display: ambulatory
```

```
  resourceType: Encounter
  id: ID_амбулаторного_посещения
  class:
    display: ambulatory
  partOf:
    reference: Encounter/ID_амбулаторного_наблюдения
```

```
  resourceType: Encounter
  id: ID_госпитализации
  identifier:
  - use: ''
    type: {}
    system: ''
    value: номер стационарной карты
    period:
      start: '2001-05-06'
      end: '2001-05-16'
    assigner: {}
  class:
    display: outpatient 
```

# [ВАРИАНТ 3] Указание номеров карт как идентификатор в иерархии из ресурсов-Encounter и\или ресурсов-EpisodeOfCare.
+: идеологически правильное размещение номеров карт в наиболее специфических ресурсах
-: необходимость поиска номера карты в иерархии из нескольких типов ресурсов

```
  resourceType: EpisodeOfCare
  id: ID_амбулаторного_наблюдения
  identifier:
  - use: ''
    type: {}
    system: ''
    value: номер амбулаторной карты
    period:
      start: '2001-05-06'
    assigner: {}
```

```
  resourceType: Encounter
  id: ID_амбулаторного_посещения
  class:
    display: ambulatory
  episodeOfCare:
    reference: EpisodeOfCare/ID_амбулаторного_наблюдения
```

```
  resourceType: Encounter
  id: ID_госпитализации
  identifier:
  - use: ''
    type: {}
    system: ''
    value: номер стационарной карты
    period:
      start: '2001-05-06'
      end: '2001-05-16'
    assigner: {}
  class:
    display: outpatient 
```

# [ВАРИАНТ 3.1] Указание номеров карт как идентификатор в иерархии из ресурсов-Encounter и\или ресурсов-EpisodeOfCare, но с обязательным заведением ресурса-EpisodeOfCare для указания в нём номера карты.
+: номер карты всегда в одном типе ресурса
-: не целевое использование ресурса EpisodeOfCare 

```
  resourceType: EpisodeOfCare
  id: ID_ведение_амбулаторной_карты
  identifier:
  - use: ''
    type: {}
    system: ''
    value: номер амбулаторное карты
    period:
      start: '2001-05-06'
    assigner: {}
```

```
  resourceType: Encounter
  id: ID_амбулаторного_посещения
  class:
    display: ambulatory
  episodeOfCare:
    reference: EpisodeOfCare/ID_ведение_амбулаторной_карты
```

```
  resourceType: EpisodeOfCare
  id: ID_ведение_стационарной_карты
  identifier:
  - use: ''
    type: {}
    system: ''
    value: номер стационарной карты
    period:
      start: '2001-05-06'
      end: '2001-05-16'
    assigner: {}
```

```
  resourceType: Encounter
  id: ID_госпитализации
  class:
    display: outpatient 
  episodeOfCare:
    reference: EpisodeOfCare/ID_ведение_стационарной_карты
```

---

@eugenekogan-spb
