### DISCUSSION TITLE
Использование профиля "Юридическое лицо" для ресурса Organization

### DISCUSSION THREAD

**Discussion by eugenekogan-spb** [fhir-ru/core#57] [Административная РГ]
## Ru Core Organization
Данный профиль определяет структуру ресурса Organization, с учетом локальных идентификаторов и справочников, для использования в российском контексте.
Целью профиля является достижение на национальном уровне согласия по ключевым особенностям ресурса Organization.
Разработчики могут использовать данный профиль для последующего уточнения (профилирования) в рамках решения своих задач.
## Identifiers
В Organization.identifier могут быть включены следующие профили элемента Identifier:
•	УИ организации по ФРМО (для юридического лица и подразделения)
•	ИНН юридического лица (для юридического лица)
•	ОГРН основной государственный регистрационный номер (для юридического лица)

## Extensions
В данном профиле не определены расширения.
## Usage Notes
При ведении государственного реестра медицинских организаций ресурс Organization следует использовать для представления юридического лица и подразделения организации.

**Comment by niquola** [comment]
## Огранизация `urn:ru:organization` или `https://fhir.ru/organization`

Профиль организации описывает субъекты хозяйственной деятельности в области здравоохранении. Этот профиль применим только к  [Юридическим Лицам](http://www.consultant.ru/document/cons_doc_LAW_5142/68642eb1daeec13480d8f283f27bc14b42b929df/) и [Индивидуальным Предпринимателям](). Для описания внутренней структуры организации (филиалы, отделы, отделения и тд) используйте профиль [Подразделение](), а для связей между юр лицами (ведомства, сети, ассоциации) - профиль [Ассоциация]().

Профиль  предназначен для описания любых организаций (ЮЛ или ИП), но специально детализирован для Медицинских Организаций.

Профиль включает из информацию о ЮЛ (реквизиты): полное и сокращённое названия, классификацию по правовой форме и виду деятельности, идентификаторы, такие как ОГРН и ИНН, юридический адрес и контактную информацию

Для Медицинских Организаций  добавлены идентфикаторы  ФРМО и номера лицензий, а также более гранулярная классификация по ЕГИСЗ

## Идентификаторы:

Ниже приведен набор возможных систем для идентификаторов

| Название  | Описание  | Код |
| ------------- | ------------- |------------- |
|  [ОГРН ](https://ru.wikipedia.org/wiki/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%BE%D0%B9_%D0%B3%D0%BE%D1%81%D1%83%D0%B4%D0%B0%D1%80%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B9_%D0%BD%D0%BE%D0%BC%D0%B5%D1%80)  | Основной государственный регистрационный номер | `urn:ru:id:ogrn` |
| [ИНН](https://ru.wikipedia.org/wiki/%D0%98%D0%B4%D0%B5%D0%BD%D1%82%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B9_%D0%BD%D0%BE%D0%BC%D0%B5%D1%80_%D0%BD%D0%B0%D0%BB%D0%BE%D0%B3%D0%BE%D0%BF%D0%BB%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D1%89%D0%B8%D0%BA%D0%B0)  |  Идентификационный номер налогоплательщика |  `urn:ru:id:org-inn`  |
| [КПП](https://ru.wikipedia.org/wiki/%D0%98%D0%B4%D0%B5%D0%BD%D1%82%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B9_%D0%BD%D0%BE%D0%BC%D0%B5%D1%80_%D0%BD%D0%B0%D0%BB%D0%BE%D0%B3%D0%BE%D0%BF%D0%BB%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D1%89%D0%B8%D0%BA%D0%B0#%D0%9A%D0%BE%D0%B4_%D0%BF%D1%80%D0%B8%D1%87%D0%B8%D0%BD%D1%8B_%D0%BF%D0%BE%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B8_%D0%BD%D0%B0_%D1%83%D1%87%D1%91%D1%82_(%D0%9A%D0%9F%D0%9F))   |  Код причины постановки на учёт   |  `urn:ru:id:kpp` |
| ФРМО OID | |  `urn:ru:id:frmo` |



## Классификация

По правовой форме `system = urn:ru:org:kind`

| Код  | Описание |
| ------------- | ------------- |
| ИП |  Индивидуальный предприниматель |
| ООО  | Общество с ограниченной ответственностью  |
| ОАО  | Акционерное общество |
| ПАО | Публичное акционерное общество |
| НКО |  Некоммерческая организация |
| ТСЖ | Товарищество собственников жилья |
| ФГБУ | ФЕДЕРАЛЬНОЕ ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕ УЧРЕЖДЕНИЕ |

По ОКВЭД   `system = urn:ru:org:okved` - Общероссийский классификатор видов экономической деятельности

| Код  | Описание |
| ------------- | ------------- |
| 86.90 |  Деятельность в области здравоохранения |
| 86.10  |  Деятельность больничных организаций  |


## Примеры

```yaml
resourceType: 'Organization'
meta:
  profile: ['urn:ru:organization']
name: Научно-производственная Фирма "ХЕЛИКС"
alias:  НПФ "ХЕЛИКС"
active: true
type:
- system: urn:ru:org:kind
   code: 'ООО'
- system: urn:ru:org:okved
   code: '86.90.9'
identifier:
- system: urn:ru:id:ogrn
   value: '1027801545925'
- system: urn:ru:org:inn
   value: '7802122535'
- system: urn:ru:frmo:oid
   value: '7802122535'
address:
- use: billing # юридический адрес
   city: САНКТ-ПЕТЕРБУРГ
   line: ['ПРОСПЕКФГБУТ БОЛЬШОЙ САМПСОНИЕВСКИЙ', '20', 'ЛИТ. А']
   postalCode: '194044'
contact:
- purpose: ....
  telecom: ...
endpoint:
- text: https://helix.ru/
  reference:  ...
```

```yaml
resourceType: 'Organization'
meta:
  profile: ['urn:ru:organization']
name: ФЕДЕРАЛЬНОЕ ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕ УЧРЕЖДЕНИЕ "ЦЕНТРАЛЬНЫЙ НАУЧНО-ИССЛЕДОВАТЕЛЬСКИЙ ИНСТИТУТ ОРГАНИЗАЦИИ И ИНФОРМАТИЗАЦИИ ЗДРАВООХРАНЕНИЯ" МИНИСТЕРСТВА ЗДРАВООХРАНЕНИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ
alias:  ФГБУ «ЦНИИОИЗ» Минздрава России
active: true
type:
- system: urn:ru:org:kind
   code: 'ФГБУ'
- system: urn:ru:org:okved
   code: '72.19'
   display:  Научные исследования и разработки в области естественных и технических наук
identifier:
- system: urn:ru:id:ogrn
   value: '1027739277235 '
- system: urn:ru:org:inn
   value: '7715217798'
address:
- use: billing # юридический адрес
   city: Москва
   line: ['ул. Добролюбова', 'д. 11']
   postalCode: '127254'
contact:
- purpose: ....
  telecom: ...
endpoint:
- text: https://mednet.ru/
  reference:  ...
```
