### DISCUSSION TITLE
Куда записать free-text поле Примечание в ресурс Patient

### DISCUSSION THREAD

**Discussion by ilya-evseev** [fhir-ru/core#92] [element]
Добрый день! Пожалуйста, подскажите, в ресурсе Patient требуется сохранить поле "примечание" - free text. Чтобы врач мог что угодно туда написать себе на заметку. Куда можно сохранить? Есть ли подходящий extension? Потому что подходящих полей в самом ресурсе я не вижу... Заранее спасибо

**Comment by JustAsWalker** [comment]
Во многих ресурсах (например, [CarePlan](https://www.hl7.org/fhir/careplan-definitions.html#CarePlan.note), [Condtion](https://www.hl7.org/fhir/condition-definitions.html#Condition.note), [Observation](https://www.hl7.org/fhir/observation-definitions.html#Observation.note), [MedicationRequest](https://www.hl7.org/fhir/medicationrequest-definitions.html#MedicationRequest.note) и [других](https://www.hl7.org/fhir/datatypes.html#Annotation)) есть атрибут `note` с кардинальностью 0..*, позволяющий указывать автора и время внесения примечания (оба необязательны) и непосредственно текст примечания. Как вариант, для ресурса `Patient` можно создать расширение аналогичного типа, а затем предложить сообществу добавить и сам атрибут в ресурс.

Альтернативный вариант - все примечания сохранять в отдельных ресурсах `Observation` с valueString.

**Comment by projkov** [comment]
Добрый день.
Вам обязательно требуется хранить текст именно в поле пациента?
Если приведете примеры более подробные, что врач может записать о пациенте, то было бы проще моделировать и думать о том, какой ресурс подойдет лучше.

Мне кажется, что для хранения заметок может подойти ресурс [DocumentReference](https://www.hl7.org/fhir/documentreference.html). 

Данный ресурс позволяет использовать для вашей задачи следующие аттрибуты:

1. content для хранения **ссылки на документ** или можно использовать прям **inline data, base64** в поле **content[0].data**
2. author для хранения ссылки на **Practitioner** или **PractitionerRole**
3. subject для хранения ссылки на **Patient**
4. type

Я вижу ресурс следующим образом:

```yaml
resourceType: DocumentReference
status: current
id: document-reference-id
subject:
  id: patient-id
  resourceType: Patient
author:
  - id: practitioner-id
    resourceType: Practitioner
date: '2022-03-16T07:50:20+00:00'
content:
  - attachment:
      data: inline-data
      contentType: text/plain
type:
  coding:
    - code: '11488-4'
      system: http://loinc.org 
      display: Consult note
```

Какие удобства:
Если выбрать тип документа, то можно запрашивать документы (в нашем случае заметки) примерно следующим образом:

```bash
GET /DocumentReference?author=practitioner-id&subject=patient-id&type=11488-4
```

**Comment by ilya-evseev** [comment]
Спасибо. Технически из-за устройства приложения хотелось бы хранить в самом ресурсе Patient. Пример заметки: "Забыл паспорт, принесет позже (надо внести номер). Конфликтный, написал жалобу в МЗ." и т.д. Нормализовать эти данные слишком сложно - требования от бизнеса именно сделать универсальное поле для таких заметок. Возможно, extension будет хорошо подходить. Спрашивал, может есть уже готовый дефинишен для таких случаев, но если нет - наверное, будем создавать

**Reply by projkov** [reply]
А заметка может быть персональная именно для врача?
Просто если вы сделаете экстеншен с обычным полем текстовым, то заметка о пациенте от 1 врача будет доступна всем. Это не проблема?

**Reply by Vrodvi** [reply]
Если делать через DocumentReference, то для такого рода заметок больше подойдёт код loinc 51851-4 "Administrative note" или ещё лучше код по локальному справочнику.

Если делать через вариант с расширением, как предложил @JustAsWalker, то получится так:
```
resourceType: Patient
id: patient-id
name:
- family: Иванов
  given:
  - Иван
extension:
- url: http://fhir.ru/fhir/Extension/patient/note
  valueAnnotation:
    authorString: Мед.регистратор Сидорова
    time: '2015-04-05T09:00:00Z'
    text: Забыл паспорт, принесет позже (надо внести номер). Конфликтный, написал
      жалобу в МЗ.
```
Вариант через расширение `note` проще, т.к. не требует указания типа заметки, но даёт возможность указать автора и время (в соответствии с типом [Annotation](https://www.hl7.org/fhir/datatypes.html#Annotation)), причём автора можно указывать или текстом или в виде ссылки, что также добавляет гибкости.

**Reply by ilya-evseev** [reply]
У нас по смыслу как раз нужна доступность всем. Но вот если даже не всем, то Annotation решает и это тоже. Видимо, пойду через extension, как в примере. Большое спасибо!

**Comment by Vrodvi** [comment]
Ещё нашёлся вариант указания примечаний\флагов\отметок через специализированный ресурс [Flag](https://www.hl7.org/fhir/flag.html) (там даже похожий пример приводится - "patient may bite"), правда в нём доступно только кодированное представление отметок, но это CodeableConcept, а значит можно указать и простой текст в CodeableConcept.text. 
Поскольку этот вариант предполагает кодирование отметок, то желательно разбить исходный текст на несколько отдельных примечаний, например:

```
resourceType: Flag
id: flag-id-1
status: active
code:
  text: Забыл паспорт, принесет позже (надо внести номер).
subject:
  reference: Patient/patient-id
encounter:
  reference: Encounter/encounter-id
```  
  

```
resourceType: Flag
id: flag-id-2
status: active
code:
  text: Конфликтный, написал жалобу в МЗ.
subject:
  reference: Patient/patient-id
encounter:
  reference: Encounter/encounter-id
```
